# Generated by Django 5.0.4 on 2024-04-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_uptime_monitor', '0002_usermapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinged_at', models.DateTimeField()),
                ('response_time', models.FloatField(null=True)),
                ('status_code', models.IntegerField(null=True)),
                ('status', models.BooleanField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_uptime_monitor.website')),
            ],
        ),
    ]
