# Generated by Django 5.0.4 on 2024-04-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_uptime_monitor', '0003_website_pinglog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PingLog',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
